services:
  app:
    build: 
      context: .
      target: runtime
      dockerfile: Dockerfile
      args:
        DEV: ${DEV:-false}
        POETRY_VERSION: ${POETRY_VERSION:-1.5.1}
    volumes:
      - .:/app
    tty: true
    stdin_open: true
volumes:
  app:

