services:
  app:
    build: 
      context: .
      target: runtime
      args:
        DEV: true
    volumes:
      - .:/app
      - .:/tmp:rm
    tty: true
    stdin_open: true
volumes:
  app:
  tmp:

