[tool.poetry]
name = "my_logger"
version = "0.1.0"
description = ""
authors = ["Lianet Sepulveda Torres <lisepul@umich.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
